# 비활성화 규칙
disabled_rules:
    - file_length                 # 파일 길이 제한 비활성화
    - trailing_whitespace         # 줄 끝 공백 무시
    - implicit_return             # 명시적 return 사용 허용

# 활성화할 옵트인 규칙
opt_in_rules:
    - empty_count                   # 빈 컬렉션은 isEmpty를 사용
    - explicit_enum_raw_value       # 열거형 원시 값 명시
    - missing_docs                  # 문서 주석 필수

# 한 줄의 최대 길이
line_length:
    warning: 100                    # 100글자에서 경고
    error: 120                      # 120 글자에서 에러
    ignores_comments: true          # 주석은 길이 제한에서 제외
    ignores_urls: true              # URL은 길이 제한에서 제외

# 네이밍 규칙
identifier_name:
    min_length: 3                   # 최소 3글자
    max_length: 40                  # 최대 40글자
    excluded:
        - id
        - x
        - y
        - i
        - j

# 연속된 빈 줄 제한
vertical_whitespace:
    max_empty_lines: 1              # 연속된 빈 줄은 1줄로 제한

